#!/bin/bash

# install dependencies
pip install -r requirements.txt

# install Detectron2
cd ~/drone-tree-id
mkdir -p lib
git clone https://github.com/facebookresearch/detectron2.git lib/detectron2
pip install -e lib/detectron2/.
