_BASE_: "Base-DeepEnt-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  PIXEL_MEAN: [120.961, 125.623, 111.1, 82.9653]
  PIXEL_STD: [1.0, 1.0, 1.0, 1.0]
