_BASE_: "Base-DeepEnt-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  DEVICE: "cpu"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
    FORMAT: "RGBA"
