_BASE_: "Base-DeepEnt-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
INPUT:
  FORMAT: "BGR"
